name: justtouch
description: "Simple mobile app for Android and iOS that lets you send files with just a tap"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  flutter_nfc_kit: ^3.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  # peerdart: ^0.5.6 # Removed - WebRTC functionality to be replaced later
  # flutter_webrtc: ^0.11.7 # Removed - WebRTC functionality to be replaced later
  ndef: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
